wordpress:
  enabled: true
  replicaCount: 1
  wordpressScheme: https
  wordpressUsername: admin
  existingSecret: 'wordpress-user-login'

  readinessProbe:
    enabled: false

  image:
    tag: 6.1.1
    repository: bitnamilegacy/wordpress

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      kubernetes.io/ingress.allow-http: "true" #Wordpress will redirect to https internally

    ingressClassName: nginx # iap-nginx
    enabled: true
    #hostname: temp.internal.napbiotec.io

    hostname: aldamex.com
    extraHosts:
      - name: www.aldamex.com
      - name: aldamexthailand.com
      - name: www.aldamexthailand.com

  service:
    type: ClusterIP

  mariadb:
    enabled: false

  externalDatabase:
    host: web-aldamex-production-mysql
    port: 3306
    database: wordpress
    user: root
    existingSecret: wordpress-db-login

mysql:
  enabled: true
  image:
    tag: 8.0.28
    repository: bitnamilegacy/mysql
  auth:
    database: wordpress
    existingSecret: wordpress-db-login
