domain1: snipeit.wintech-thai.com
domain2: snipeit.napbiotec.com

snipeit:
  enabled: true
  config:
    snipeit:
      url: https://snipeit.napbiotec.com
      key: base64:uxA0D1SdxZJ5afqbNadLOoPkVzjdmSgneILipsFfclI=

  mysql:
    enabled: true

  ingress:
    enabled: false
