domain1: snipeit.wintech-thai.com
domain2: snipeit.napbiotec.com

snipeit:
  enabled: true
  config:
    snipeit:
      url: https://snipeit.wintech-thai.com
    externalSecrets: "snipeit-secret"

  mysql:
    enabled: true

  ingress:
    enabled: false
