apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eagle-codecheck-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "true" #Wordpress will redirect to https internally
spec:
  tls:
    - hosts:
      - {{ .Values.domainWordpress1 }}
      - www.{{ .Values.domainWordpress1 }}
      #secretName: eagle-cert
  rules:
    - host: {{ .Values.domainWordpress1 }}
      http:
        paths:
          - path: /epeagle
            pathType: Prefix
            backend:
              service:
                name: codecheck-external-ip
                port:
                  number: 80
  
    - host: www.{{ .Values.domainWordpress1 }}
      http:
        paths:
          - path: /epeagle
            pathType: Prefix
            backend:
              service:
                name: codecheck-external-ip
                port:
                  number: 80
