---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snipeit-secret
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: snipeit-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "APP_KEY" # For Wordpress
      remoteRef:
        key: initial-secret-preset
        property: SNIPEIT_KEY
